if (EXISTS /opt/devel-gcc-13-toolchain.cmake)
    include(/opt/devel-gcc-13-toolchain.cmake)
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libstdc++ -static-libgcc")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libstdc++ -static-libgcc")
endif ()
