if (EXISTS /opt/gcc-toolset-15-toolchain.cmake)
    include(/opt/gcc-toolset-15-toolchain.cmake)
    set(CMAKE_EXE_LINKER_FLAGS_INIT "-static-libstdc++ -static-libgcc")
    set(CMAKE_SHARED_LINKER_FLAGS_INIT "-static-libstdc++ -static-libgcc")
endif ()
